/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: GRaphail (https://sketchfab.com/bawara)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lowpoly-desk-a879d9652957401a95f88dee94314358
title: Lowpoly Desk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lowpoly.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
          <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
          <group position={[-0.34, 0.76, -0.21]} rotation={[0, 0.78, 0]}>
            <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
          </group>
          <group position={[-0.57, 1.2, 0.96]} rotation={[1.03, 0.52, -0.69]}>
            <group rotation={[-0.31, 0, 0]}>
              <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
            </group>
            <group rotation={[-1.37, 0, 0]}>
              <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
            </group>
            <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
            <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
          </group>
          <group position={[-0.54, 1.59, 0.11]} rotation={[0, -0.09, 0]} scale={0.25}>
            <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
            <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
          </group>
          <group position={[0, 0.1, 0]}>
            <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
          </group>
          <group position={[0, 1.36, -0.76]} rotation={[0, 0, 0.08]}>
            <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
          </group>
          <group position={[0.16, 1.46, -0.76]} rotation={[0, 0, -0.13]}>
            <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
          </group>
          <group position={[0.02, 1.59, -0.76]} rotation={[0, 0, 0.05]}>
            <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
          </group>
          <group position={[0.97, 0, -0.5]} rotation={[0, 0.73, 0]} scale={[0.96, 0.96, 0.96]}>
            <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
            <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
            <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
          </group>
          <group position={[0.17, 0, 0.16]} rotation={[0, -0.74, 0]}>
            <mesh geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
          </group>
          <group position={[0.14, 0.76, -0.36]} rotation={[0, 0.08, 0]}>
            <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
          </group>
          <group position={[0.13, 0.76, -0.34]} rotation={[0, 0.26, 0]}>
            <mesh geometry={nodes.Object_35.geometry} material={nodes.Object_35.material} />
            <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
            <mesh geometry={nodes.Object_37.geometry} material={nodes.Object_37.material} />
          </group>
          <group position={[-0.61, 0.92, 0.54]} rotation={[0, 1.33, 0]} scale={0.33}>
            <mesh geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
          </group>
          <group position={[0.4, 0, -0.5]} scale={0.26}>
            <mesh geometry={nodes.Object_41.geometry} material={nodes.Object_41.material} />
          </group>
          <group position={[0.4, 0.32, -0.5]} scale={0.18}>
            <mesh geometry={nodes.Object_43.geometry} material={nodes.Object_43.material} />
          </group>
          <group position={[1.06, 0.75, 0.4]} rotation={[0, -1.51, 0]}>
            <mesh geometry={nodes.Object_45.geometry} material={nodes.Object_45.material} />
            <mesh geometry={nodes.Object_46.geometry} material={nodes.Object_46.material} />
            <mesh geometry={nodes.Object_47.geometry} material={nodes.Object_47.material} />
          </group>
          <group position={[1.03, 0.81, 0.62]} rotation={[-1.59, 0.08, -1.35]}>
            <mesh geometry={nodes.Object_49.geometry} material={nodes.Object_49.material} />
            <mesh geometry={nodes.Object_50.geometry} material={nodes.Object_50.material} />
          </group>
          <group position={[0.53, 0.76, -0.28]} rotation={[0, 0.66, 0]}>
            <mesh geometry={nodes.Object_52.geometry} material={nodes.Object_52.material} />
            <mesh geometry={nodes.Object_53.geometry} material={nodes.Object_53.material} />
          </group>
          <group position={[0.66, 0.76, -0.62]}>
            <mesh geometry={nodes.Object_55.geometry} material={nodes.Object_55.material} />
          </group>
          <group position={[0.61, 0.84, -0.63]}>
            <mesh geometry={nodes.Object_57.geometry} material={nodes.Object_57.material} />
          </group>
          <group position={[-0.57, 0.76, 0.53]} rotation={[-Math.PI, 1.53, -Math.PI]}>
            <mesh geometry={nodes.Object_59.geometry} material={nodes.Object_59.material} />
            <mesh geometry={nodes.Object_60.geometry} material={nodes.Object_60.material} />
          </group>
          <group position={[-0.42, 0, 0.58]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_62.geometry} material={nodes.Object_62.material} />
            <mesh geometry={nodes.Object_63.geometry} material={nodes.Object_63.material} />
            <mesh geometry={nodes.Object_64.geometry} material={nodes.Object_64.material} />
          </group>
          <mesh geometry={nodes.Object_66.geometry} material={nodes.Object_66.material} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.tile} />
          <group position={[0.74, 1.76, -0.76]}>
            <mesh geometry={nodes.Object_69.geometry} material={materials.M_tableau} />
          </group>
          <group position={[-0.57, 1.59, -0.38]} rotation={[-0.07, 1.22, 0.06]}>
            <mesh geometry={nodes.Object_71.geometry} material={nodes.Object_71.material} />
          </group>
          <group position={[-0.59, 1.82, -0.59]} rotation={[1.22, 0.88, -0.82]}>
            <mesh geometry={nodes.Object_73.geometry} material={materials.material_0} />
          </group>
          <group position={[0.2, 0.76, -0.66]}>
            <mesh geometry={nodes.Object_75.geometry} material={nodes.Object_75.material} />
          </group>
          <group position={[0.17, 0.76, -0.66]} rotation={[0, 0, -0.55]}>
            <mesh geometry={nodes.Object_77.geometry} material={nodes.Object_77.material} />
          </group>
          <group position={[0.16, 0.76, -0.65]} rotation={[0, 0.84, -0.55]}>
            <mesh geometry={nodes.Object_79.geometry} material={nodes.Object_79.material} />
          </group>
          <group position={[0.23, 0.76, -0.67]} rotation={[Math.PI, -0.76, 2.59]}>
            <mesh geometry={nodes.Object_81.geometry} material={nodes.Object_81.material} />
          </group>
          <group position={[-0.59, 0.76, -0.23]} rotation={[0, 0.96, 0]} scale={0.7}>
            <mesh geometry={nodes.Object_83.geometry} material={nodes.Object_83.material} />
            <mesh geometry={nodes.Object_84.geometry} material={nodes.Object_84.material} />
          </group>
          <group position={[-0.21, 0.76, -0.59]} rotation={[0, 0.55, 0]} scale={[0.7, 0.7, 0.7]}>
            <mesh geometry={nodes.Object_86.geometry} material={nodes.Object_86.material} />
            <mesh geometry={nodes.Object_87.geometry} material={nodes.Object_87.material} />
          </group>
          <group position={[-0.5, 0, 0.98]}>
            <mesh geometry={nodes.Object_89.geometry} material={nodes.Object_89.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lowpoly.gltf')
